#----------------------------------------------------------------------------------------------
# usage message 
usage=\
"[usage] example: bash calibrate.sh -i \"images0 images1...\" -t <path to opencv calibrate executable file>"
echo $usage

#----------------------------------------------------------------------------------------------
# check flags
while getopts "a:i:t:h" arg; do
	case $arg in
		i)
			echo "input folders provided: $OPTARG"
			input_folders=$OPTARG
			;;
		t) 
			echo "opencv calibrate executable file provided $OPTARG"
			opencv_calibrate=$OPTARG
			;;
		h)
			exit
	esac
done

#----------------------------------------------------------------------------------------------
# default value
if [ -z "$input_folders" ]; then
	input_folders="images"
	echo "Input_folder not provided, use $input_folders by default"
fi
if [ -z "$opencv_calibrate" ]; then
	opencv_calibrate="@CMAKE_CURRENT_BINARY_DIR@/opencv_camera_calibration/calibration"
	echo "opencv calibrate program not provided, use $opencv_calibrate by default"
	echo "Calibration program takes `dirname $0`/calibration_input.xml as input, where \"image_list.xml\" is specified as image list"
	echo "\"image_list.xml\" will be generated by this script, from folders specified by -s opt"
fi

#----------------------------------------------------------------------------------------------
# create image name lists
name_list=""
for input_folder in $input_folders; do
	echo "traversing $input_folder"
	if [ ! -d "$input_folder" ]; then
		echo "[error] $input_folder doesn't exist!"
		exit
	fi

	# for each png file in $input_folder/$arm folder
	for file in $input_folder/*.png; do
		name_list="$name_list$file\n"
	done
done

#----------------------------------------------------------------------------------------------
# create image_list.xml
output="image_list.xml"
echo -e \
"<?xml version=\"1.0\"?>\n\
<opencv_storage>\n\
<images>\n\
$name_list\
</images>\n\
</opencv_storage>" \
> $output

echo "$output prepared, ready to calibrate"

#----------------------------------------------------------------------------------------------
# calibrate
sh_file_dir=`dirname $0`
$opencv_calibrate $sh_file_dir/calibration_input.xml
